workspace = { members = ["derived-cms-derive"] }
[package]
name = "derived-cms"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.3"
chrono = { version = "0.4.31", features = ["serde"] }
convert_case = "0.6.0"
derive_more = "0.99.17"
derived-cms-derive = { version = "0.1.0", path = "derived-cms-derive" }
generic-array = "1.0.0"
include_dir = "0.7.3"
maud = { git = "https://github.com/lambda-fairy/maud", branch = "main", version = "0.25.0", features = [
    "axum",
] }
mime_guess = "2.0.4"
ormlite = { git = "https://github.com/nitn3lav/ormlite", branch = "main" }
regex = "1.10.2"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.111"
serde_qs = { version = "0.12.0", features = ["axum"] }
sqlx = { version = "0.7.3" }
tracing = "0.1.40"
uuid = { version = "1.6.1", features = ["v4"] }

[dev-dependencies]
tokio = { version = "1.35.1", features = ["full"] }

[features]
json = ["sqlx/json"]
