[package]
name = "derived-cms-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
attribute-derive = "0.8.1"
itertools = "0.12.0"
proc-macro-crate = "2.0.1"
proc-macro2 = "1.0.73"
quote = "1.0.34"
syn = { version = "2.0.44", features = ["full"] }

[lib]
proc-macro = true
